<?php

return [
    'domain' => 'ttrd.fr',
    'brand' => 'TTRD',
    'product' => 'STT',
    'title' => 'Statut',
    'history_days' => 90,
    'probe_interval' => 60,
    'degraded_ms' => 2000,
    'timeout' => 12,
    'connect_timeout' => 6,
    'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 STT-TTRD/1.0',
    'discover_ttl' => 21600,
    'watch' => [
        ['host' => 'lacavernechaude.fr', 'label' => 'La Caverne', 'group' => 'externe'],
        ['host' => 'uploads.lacavernechaude.fr', 'label' => 'Caverne CDN', 'group' => 'externe'],
        ['host' => 'athena.ttrd.fr', 'label' => 'Athena', 'group' => 'ttrd'],
        ['host' => 'env.ttrd.fr', 'label' => 'Env', 'group' => 'ttrd'],
        ['host' => 'env-2.ttrd.fr', 'label' => 'Env 2', 'group' => 'ttrd'],
        ['host' => 'gd.ttrd.fr', 'label' => 'GD', 'group' => 'ttrd'],
        ['host' => 'guichet-pro.ttrd.fr', 'label' => 'Guichet Pro', 'group' => 'ttrd'],
        ['host' => 'jurinum.ttrd.fr', 'label' => 'Jurinum', 'group' => 'ttrd'],
        ['host' => 'la-popotte.ttrd.fr', 'label' => 'La Popotte', 'group' => 'ttrd'],
        ['host' => 'le-refuge.ttrd.fr', 'label' => 'Le Refuge', 'group' => 'ttrd'],
        ['host' => 'lesfilsdepute.ttrd.fr', 'label' => 'Les fils de pute', 'group' => 'ttrd'],
        ['host' => 'sso.ttrd.fr', 'label' => 'SSO', 'group' => 'ttrd'],
        ['host' => 'vlm.ttrd.fr', 'label' => 'VLM', 'group' => 'ttrd'],
        ['host' => 'uploads.ttrd.fr', 'label' => 'Uploads', 'group' => 'ttrd'],
    ],
];
