<?php

return [
    'domain' => 'ttrd.fr',
    'brand' => 'TTRD',
    'product' => 'STT',
    'title' => 'Statut',
    'history_days' => 90,
    'probe_interval' => 60,
    'degraded_ms' => 2000,
    'timeout' => 12,
    'connect_timeout' => 6,
    'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 STT-TTRD/1.0',
    'discover_ttl' => 21600,
    'exclude_hosts' => [],
    'labels' => [
        'ttrd.fr' => 'Racine',
        'stt.ttrd.fr' => 'Statut',
        'la-popotte.ttrd.fr' => 'La Popotte',
        'athena.ttrd.fr' => 'Athena',
        'filsdepute.ttrd.fr' => 'Filsdepute',
        'lesfilsdepute.ttrd.fr' => 'Lesfilsdepute',
        'fils-de-pute-de-smurf.ttrd.fr' => 'Smurf',
        'le-refuge.ttrd.fr' => 'Le Refuge',
        'env.ttrd.fr' => 'Env',
        'env-2.ttrd.fr' => 'Env 2',
        'certificate.ttrd.fr' => 'Certificate',
        'cb.ttrd.fr' => 'CB',
        'guichet-pro.ttrd.fr' => 'Guichet Pro',
        'license.ttrd.fr' => 'License',
        'vlm.ttrd.fr' => 'VLM',
        'airsoft.ttrd.fr' => 'Airsoft',
        'memoria.ttrd.fr' => 'Memoria',
        'caca.ttrd.fr' => 'Caca',
        'twitch.ttrd.fr' => 'Twitch',
        'api-atak.ttrd.fr' => 'API Atak',
        'jurinum.ttrd.fr' => 'Jurinum',
        'sso.ttrd.fr' => 'SSO',
        'gav.ttrd.fr' => 'GAV',
        'natinf.ttrd.fr' => 'Natinf',
        'lrpgn.ttrd.fr' => 'LRPGN',
        'uploads.ttrd.fr' => 'Uploads',
        'gd.ttrd.fr' => 'GD',
        'patryk.ttrd.fr' => 'Patryk',
        'crypto.ttrd.fr' => 'Crypto',
        'lacavernechaude.fr' => 'La Caverne Chaude',
        'uploads.lacavernechaude.fr' => 'Caverne CDN',
    ],
    'extra_sites' => [
        ['host' => 'lacavernechaude.fr', 'label' => 'La Caverne Chaude', 'group' => 'externe'],
        ['host' => 'uploads.lacavernechaude.fr', 'label' => 'Caverne CDN', 'group' => 'externe'],
    ],
    'migration' => [
        'source' => 'Premium Web Hosting',
        'account' => 'u416380327',
        'home' => '/home/u416380327',
        'domains' => '/home/u416380327/domains',
        'apex_public' => '/home/u416380327/domains/ttrd.fr/public_html',
        'wordpress' => false,
        'vps_id' => '1934687',
        'vps_ip' => '72.62.22.55',
        'flagship' => ['ttrd.fr', 'athena.ttrd.fr', 'la-popotte.ttrd.fr'],
    ],
];
